openapi: 3.0.0
info:
  title: Simple API
  description: A simple API to demonstrate OpenAPI specification
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local server

paths:
  /items:
    get:
      summary: Retrieve a list of items
      responses:
        '200':
          description: A list of items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
    post:
      summary: Create a new item
      requestBody:
        description: Item to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
      responses:
        '201':
          description: Item created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'

components:
  schemas:
    Item:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: "Item name"
        description:
          type: string
          example: "Item description"
