openapi: 3.0.0
info:
  title: Simple API
  description: A simple API to demonstrate OpenAPI specification
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local server

paths:
  /policies:
    post:
      summary: Create an authorization policy for the given API key
      requestBody:
        $ref: '#/components/requestBodies/CreatePolicyRequest'
      responses:
        200:
          description: The created policy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Policy'
  /query:
    post:
      summary: Execute a SQLite query
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                query:
                  type: string
      responses:
        200:
          description: The results of the query
          content:
            application/json:
              schema:
                type: object
        401:
          description: Unauthenticated. Missing a valid API key.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        403:
          description: Unauthorized to execute the given query
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api_keys:
    post:
      summary: Create an API key
      responses:
        201:
          $ref: '#/components/responses/APIKeyResponse'

components:
  securitySchemes:
    ApiKeyAuth:
      type: http
      scheme: basic
  requestBodies:
    CreatePolicyRequest:
      description: The authorization policy you'd like to create
      content:
        application/json:
          schema:
            type: object
            required:
              - principal
              - effect
            properties:
              principal:
                type: string
              actions:
                type: array
                uniqueItems: true
                items:
                  $ref: '#/components/schemas/Action'
              resource:
                type: string
              effect:
                enum:
                  - allow
                  - deny
  responses:
    APIKeyResponse:
      description: A new API key
      content:
        application/json:
          schema:
            type: object
            properties:
              api_key:
                type: string

  schemas:
    Action:
      enum:
        - select
        - insert
        - update
        - delete
    Policy:
      type: object
      required:
        - principal
        - effect
        - id
      properties:
        id:
          type: string
        principal:
          type: string
        actions:
          type: array
          uniqueItems: true
          items:
            $ref: '#/components/schemas/Action'
        resource:
          type: string
        effect:
          enum:
            - allow
            - deny
    Error:
      type: object
      properties:
        message:
          type: string

security:
  - ApiKeyAuth: []
