openapi: 3.0.0
info:
  title: Simple API
  description: A simple API to demonstrate OpenAPI specification
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local server

paths:
  /policies:
    post:
      summary: Create an authorization policy for the given API key
      requestBody:
        $ref: '#/components/requestBodies/CreatePolicyRequest'
      responses:
        201:
          description: The created policy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Policy'
    get:
      summary: List authorization policies for the given API key
      responses:
        200:
          description: The given API key's policies
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Policy'
  /query:
    post:
      summary: Execute a SQLite query
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                query:
                  type: string
      responses:
        200:
          description: The results of the query
          content:
            application/json:
              schema:
                type: object
        401:
          $ref: '#/components/responses/ErrorResponse'
        403:
          $ref: '#/components/responses/ErrorResponse'
        400:
          $ref: '#/components/responses/ErrorResponse'
  /api_keys:
    post:
      summary: Create an API key
      responses:
        201:
          $ref: '#/components/responses/APIKeyResponse'

components:
  securitySchemes:
    ApiKeyAuth:
      type: http
      scheme: basic
  requestBodies:
    CreatePolicyRequest:
      description: The authorization policy you'd like to create
      content:
        application/json:
          schema:
            type: object
            required:
              - effect
            properties:
              actions:
                type: array
                uniqueItems: true
                items:
                  $ref: '#/components/schemas/Action'
              resource:
                type: string
              effect:
                enum:
                  - allow
                  - deny
  responses:
    ErrorResponse:
      description: An error occurred
      content:
        application/json:
          schema:
            type: object
            required:
              - message
            properties:
              message:
                type: string
              errors:
                type: array
                items:
                  type: object
    APIKeyResponse:
      description: A new API key
      content:
        application/json:
          schema:
            type: object
            properties:
              api_key:
                type: string

  schemas:
    Action:
      enum:
        - select
        - insert
        - update
        - delete
    Policy:
      type: object
      required:
        - principal
        - effect
        - id
      properties:
        id:
          type: string
        principal:
          type: string
        actions:
          type: array
          uniqueItems: true
          items:
            $ref: '#/components/schemas/Action'
        resource:
          type: string
        effect:
          enum:
            - allow
            - deny
